// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['NotesHandler']['CreateNote'](arg1, arg2, arg3, arg4);
}

export function CreateNoteWithTags(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['NotesHandler']['CreateNoteWithTags'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteNoteByID(arg1) {
  return window['go']['backend']['NotesHandler']['DeleteNoteByID'](arg1);
}

export function GetNoteByID(arg1) {
  return window['go']['backend']['NotesHandler']['GetNoteByID'](arg1);
}

export function GetNotes() {
  return window['go']['backend']['NotesHandler']['GetNotes']();
}

export function UpdateNoteByID(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['NotesHandler']['UpdateNoteByID'](arg1, arg2, arg3, arg4, arg5, arg6);
}
